### ISSUE TITLE
Link of https://draculatheme.com/foobar is broken

### ISSUE THREAD

**Issue by Anselmoo** [dracula/template#12]
Seems that the [https://draculatheme.com/foobar](https://draculatheme.com/foobar) is broken

**Comment by farid-temuri** [comment]
It is intended not to work, for example you add dracula theme for 'code edotor' -> then you will have all information about installation https://draculatheme.com/code-editor.

**Comment by Anselmoo** [comment]
Sorry @am-i-farid , I don't get it ... also seems to be not working [https://draculatheme.com/code-editor]( https://draculatheme.com/code-editor)
