### ISSUE TITLE
Change default branch name?

### ISSUE THREAD

**Issue by jrdnbradford** [dracula/template#15]
Given changes referenced in https://github.com/dracula/dracula-theme/issues/915 , the site now supports default branch names for repos other than `master`. This makes it as good a time as any to change this template repo's default branch from `master` to something like `main` so that future Dracula repos created from this template get a different branch.

**Comment by luxonauta** [comment]
Thanks, Jordan! I adjusted it, and I left another helper file for future contributors: https://github.com/dracula/template/commit/291aa546dbf6e95ba4eabec737df8d348125c379. 🪴
