### ISSUE TITLE
Outdated GitHub templates

### ISSUE THREAD

**Issue by alexherbo2** [dracula/template#2]
GitHub reports the files in [`.github`] are old versions of the templates.

[`.github`]: https://github.com/dracula/template/tree/master/.github

**Comment by bsoyka** [comment]
Since it seems this repo just needs one issue template, the old version may actually be better. Check out [this page](https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates).

**Comment by zenorocha** [comment]
Thanks for reporting! I decided to remove the template since each theme has a different set of needs.
