### ISSUE TITLE
Instructions page is down. Error 404.

### ISSUE THREAD

**Issue by Dhyfer1** [dracula/template#4]
Hi.

I need to know what the instructions are, but it is impossible if the page [https://draculatheme.com/x](url) is down. So, is there another place to see the instructions or should I wait until the page is back online?

Thanks.

![CopyQ naSbTF](https://user-images.githubusercontent.com/50301201/104251164-19f29a80-543d-11eb-849c-45ef1d7838e6.png)

**Comment by zenorocha** [comment]
This repository is a template for people to generate new themes. For instructions, you can look at: https://draculatheme.com/contribute
