### ISSUE TITLE
The Dracula Theme Website's down. 

### ISSUE THREAD

**Issue by TheArithmetic** [dracula/template#8]
The Dracula Theme Template website seems to be down because of an internal server-side error. [](url)
![Screen Shot 2021-12-14 at 9 21 00 PM](https://user-images.githubusercontent.com/71181719/146032417-09c0a509-c658-433f-a8cb-50a1ecce6a15.png)

**Comment by zenorocha** [comment]
The https://draculatheme.com/x link is a placeholder, it's supposed to be replaced by the theme author.
